# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the working directory to /app
WORKDIR /usr/local/docker/balionis-java0

# Copy the current directory contents into the container at /app
ADD build/distributions/balionis-java0-1.0-SNAPSHOT.tar.gz /usr/local/docker/balionis-java0

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Define environment variable
ENV JAVA_HOME /usr/local/jdk1.8.0

# Run app.py when the container launches
CMD ["python", "bin/app.py", "--p1", "123", "--p2", "abc"]
