version: "3"
services:
  myapp:
    image: baliarvy/balionis-java0:latest
    volumes:
      - /usr/local/jdk1.8.0:/usr/local/jdk1.8.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "40000:8080"
    networks:
      - webnet
networks:
  webnet:
